### ISSUE TITLE
Support for repositories definitions with * and **

### ISSUE THREAD

**Issue by alexander-schranz** [soyuka/pmu#2]
**Description**  

Composer does not require to define all local repositories directly. You can give even a whole directory which contain multiple packages in it, this makes adding new packages a lot easier in mono repositories as you don't need to add them everytime to the your composer.json files:

```json
    "repositories": [
        {
            "type": "path",
            "url": "./packages/*",
            "options": {
                "symlink": true
            }
        }
    ],
```

**Example**  

https://github.com/schranz-search/schranz-search/blob/d9ebf86828f71c3189f903950b26f893367f6f12/.examples/symfony/composer.json#L106-L121

**Comment by soyuka** [comment]
for real? I need to see how to fit that into my code
